$(document).ready(function(){
    $('#hover_').hover(function(){
        $(this).hide();
    },
    function(){
        $(this).show();
    });
    $('#focus_').focus(function(){
        $(this).css('background-color', 'orange');
        $(this).css('height', '30px');
    });
    $('#focus_').blur(function(){
        $(this).css('background-color', 'white');
        $(this).css('height', '20px');
    });
    $('#button_').click(function(){
        $('#tong').toggle(500);
    });
    $('#doge').animate({
        left:'5%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'10%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'15%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'20%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'25%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'30%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'35%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'40%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'45%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'50%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'55%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'60%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'65%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'70%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'75%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'80%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'85%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'90%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'85%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'80%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'75%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'70%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'65%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'60%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'55%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'50%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'45%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'40%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'35%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'30%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'25%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'20%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'15%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'10%',
        top:'70%'
    },100);
    $('#doge').animate({
        left:'5%',
        top:'0%'
    },100);
    $('#doge').animate({
        left:'0%',
        top:'70%'
    },100);
});